var fullBank = [
{type:"original", base:"あたたかい", en:"warm", jp:"あたたかいです", stage:1, diff:"easy"},
{type:"original", base:"あたらしい", en:"new", jp:"あたらしいです", stage:1, diff:"easy"},
{type:"original", base:"あつい", en:"hot", jp:"あついです", stage:1, diff:"easy"},
{type:"original", base:"あぶない", en:"dangerous", jp:"あぶないです", stage:1, diff:"mixed"},
{type:"original", base:"いそがしい", en:"busy", jp:"いそがしいです", stage:1, diff:"mixed"},
{type:"original", base:"いい", en:"good", jp:"いいです", stage:1, diff:"easy"},
{type:"original", base:"おおい", en:"many", jp:"おおいです", stage:1, diff:"mixed"},
{type:"original", base:"おもしろい", en:"interesting", jp:"おもしろいです", stage:1, diff:"easy"},
{type:"original", base:"おそい", en:"late", jp:"おそいです", stage:1, diff:"mixed"},
{type:"original", base:"かっこいい", en:"stylish", jp:"かっこいいです", stage:1, diff:"easy"},
{type:"original", base:"かわいい", en:"cute", jp:"かわいいです", stage:1, diff:"easy"},
{type:"original", base:"ひろい", en:"spacious", jp:"ひろいです", stage:1, diff:"mixed"},
{type:"original", base:"せまい", en:"narrow", jp:"せまいです", stage:1, diff:"mixed"},
{type:"original", base:"まるい", en:"round", jp:"まるいです", stage:1, diff:"mixed"},
{type:"original", base:"めずらしい", en:"rare", jp:"めずらしいです", stage:1, diff:"mixed"},
{type:"original", base:"むしあつい", en:"hot and humid", jp:"むしあついです", stage:1, diff:"mixed"},
{type:"original", base:"むずかしい", en:"difficult", jp:"むずかしいです", stage:1, diff:"mixed"},
{type:"original", base:"ながい", en:"long", jp:"ながいです", stage:1, diff:"easy"},
{type:"original", base:"さむい", en:"cold", jp:"さむいです", stage:1, diff:"easy"},
{type:"original", base:"すごい", en:"great", jp:"すごいです", stage:1, diff:"mixed"},
{type:"original", base:"すずしい", en:"cool", jp:"すずしいです", stage:1, diff:"easy"},
{type:"original", base:"たかい", en:"expensive", jp:"たかいです", stage:1, diff:"easy"},
{type:"original", base:"たのしい", en:"fun", jp:"たのしいです", stage:1, diff:"easy"},
{type:"original", base:"ちいさい", en:"small", jp:"ちいさいです", stage:1, diff:"easy"},
{type:"original", base:"つよい", en:"strong", jp:"つよいです", stage:1, diff:"mixed"},
{type:"original", base:"とおい", en:"far", jp:"とおいです", stage:1, diff:"mixed"},
{type:"original", base:"はやい", en:"early", jp:"はやいです", stage:1, diff:"mixed"},
{type:"original", base:"ふるい", en:"old", jp:"ふるいです", stage:1, diff:"easy"},
{type:"original", base:"わかい", en:"young", jp:"わかいです", stage:1, diff:"mixed"},
{type:"original", base:"やすい", en:"cheap", jp:"やすいです", stage:1, diff:"easy"},
{type:"original", base:"しろい", en:"white", jp:"しろいです", stage:1, diff:"easy"},
{type:"original", base:"くろい", en:"black", jp:"くろいです", stage:1, diff:"easy"},
{type:"original", base:"あかい", en:"red", jp:"あかいです", stage:1, diff:"easy"},
{type:"original", base:"あおい", en:"blue", jp:"あおいです", stage:1, diff:"easy"},
{type:"original", base:"きいろい", en:"yellow", jp:"きいろいです", stage:1, diff:"easy"},
{type:"original", base:"いろいろ", en:"various", jp:"いろいろです", stage:1, diff:"mixed"},
{type:"original", base:"げんき", en:"energetic", jp:"げんきです", stage:1, diff:"mixed"},
{type:"original", base:"かんたん", en:"easy", jp:"かんたんです", stage:1, diff:"mixed"},
{type:"original", base:"きれい", en:"beautiful", jp:"きれいです", stage:1, diff:"easy"},
{type:"original", base:"しずか", en:"quiet", jp:"しずかです", stage:1, diff:"easy"},
{type:"original", base:"たいへん", en:"tough", jp:"たいへんです", stage:1, diff:"mixed"},
{type:"original", base:"だいじょうぶ", en:"okay", jp:"だいじょうぶです", stage:1, diff:"mixed"},
{type:"original", base:"とくい", en:"good at", jp:"とくいです", stage:1, diff:"mixed"},
{type:"original", base:"にがて", en:"not good at", jp:"にがてです", stage:1, diff:"mixed", needNote:true},
{type:"original", base:"にぎやか", en:"lively", jp:"にぎやかです", stage:1, diff:"mixed"},
{type:"original", base:"ひま", en:"free", jp:"ひまです", stage:1, diff:"mixed"},
{type:"original", base:"べんり", en:"convenient", jp:"べんりです", stage:1, diff:"mixed"},
{type:"original", base:"まっすぐ", en:"straight", jp:"まっすぐです", stage:1, diff:"mixed"},
{type:"original", base:"ゆうめい", en:"famous", jp:"ゆうめいです", stage:1, diff:"mixed"},
{type:"original", base:"おしゃれ", en:"fashionable", jp:"おしゃれです", stage:1, diff:"mixed"},
{type:"original", base:"すき", en:"favorite", jp:"すきです", stage:1, diff:"easy"},
{type:"original", base:"きらい", en:"dislike", jp:"きらいです", stage:1, diff:"mixed"},
{type:"neg", base:"あたたかい", en:"not warm", jp:"あたたかくないです", stage:1, diff:"easy"},
{type:"neg", base:"あつい", en:"not hot", jp:"あつくないです", stage:1, diff:"easy"},
{type:"neg", base:"かっこいい", en:"not stylish", jp:"かっこよくないです", stage:1, diff:"mixed"},
{type:"neg", base:"かわいい", en:"not cute", jp:"かわいくないです", stage:1, diff:"easy"},
{type:"neg", base:"ながい", en:"not long", jp:"ながくないです", stage:1, diff:"easy"},
{type:"neg", base:"すずしい", en:"not cool", jp:"すずしくないです", stage:1, diff:"easy"},
{type:"neg", base:"たかい", en:"not expensive", jp:"たかくないです", stage:1, diff:"easy"},
{type:"neg", base:"ちいさい", en:"not small", jp:"ちいさくないです", stage:1, diff:"easy"},
{type:"neg", base:"しろい", en:"not white", jp:"しろくないです", stage:1, diff:"easy"},
{type:"neg", base:"せまい", en:"not narrow", jp:"せまくないです", stage:1, diff:"mixed"},
{type:"neg", base:"おもしろい", en:"not interesting", jp:"おもしろくないです", stage:1, diff:"mixed"},
{type:"neg", base:"しずか", en:"not quiet", jp:"しずかじゃないです", stage:1, diff:"easy"},
{type:"neg", base:"きれい", en:"not beautiful", jp:"きれいじゃないです", stage:1, diff:"easy"},
{type:"neg", base:"すき", en:"not favorite", jp:"すきじゃないです", stage:1, diff:"easy"},
{type:"neg", base:"べんり", en:"not convenient", jp:"べんりじゃないです", stage:1, diff:"mixed"},
{type:"neg", base:"げんき", en:"not energetic", jp:"げんきじゃないです", stage:1, diff:"mixed"},
{type:"neg", base:"あぶない", en:"not dangerous", jp:"あぶなくないです", stage:1, diff:"mixed"},
{type:"neg", base:"むずかしい", en:"not difficult", jp:"むずかしくないです", stage:1, diff:"mixed"},
{type:"past", base:"やすい", en:"was cheap", jp:"やすかったです", stage:2, diff:"easy"},
{type:"past", base:"やすい", en:"was not cheap", jp:"やすくなかったです", stage:2, diff:"easy"},
{type:"past", base:"すずしい", en:"was cool", jp:"すずしかったです", stage:2, diff:"easy"},
{type:"past", base:"すずしい", en:"was not cool", jp:"すずしくなかったです", stage:2, diff:"easy"},
{type:"past", base:"かっこいい", en:"was stylish", jp:"かっこよかったです", stage:2, diff:"mixed"},
{type:"past", base:"たのしい", en:"was fun", jp:"たのしかったです", stage:2, diff:"easy"},
{type:"past", base:"たのしい", en:"was not fun", jp:"たのしくなかったです", stage:2, diff:"mixed"},
{type:"past", base:"しずか", en:"was quiet", jp:"しずかでした", stage:2, diff:"easy"},
{type:"past", base:"しずか", en:"was not quiet", jp:"しずかじゃなかったです", stage:2, diff:"easy"},
{type:"past", base:"きれい", en:"was beautiful", jp:"きれいでした", stage:2, diff:"easy"},
{type:"past", base:"きれい", en:"was not beautiful", jp:"きれいじゃなかったです", stage:2, diff:"mixed"},
{type:"past", base:"おしゃれ", en:"fashionable", jp:"おしゃれでした", stage:2, diff:"mixed"},
{type:"past", base:"ひろい", en:"spacious", jp:"ひろかったです", stage:2, diff:"mixed"},
{type:"past", base:"せまい", en:"narrow", jp:"せまかったです", stage:2, diff:"mixed"},
{type:"past", base:"あつい", en:"hot", jp:"あつかったです", stage:2, diff:"easy"},
{type:"past", base:"あつい", en:"not hot", jp:"あつくなかったです", stage:2, diff:"easy"},
{type:"past", base:"げんき", en:"energetic", jp:"げんきでした", stage:2, diff:"mixed"},
{type:"past", base:"げんき", en:"not energetic", jp:"げんきじゃなかったです", stage:2, diff:"mixed"},
{type:"past", base:"ちいさい", en:"small", jp:"ちいさかったです", stage:2, diff:"easy"},
{type:"te", base:"かわいい+しろい", en:"cute and white", jp:"かわいくてしろいです", stage:3, diff:"easy"},
{type:"te", base:"かっこいい+くろい", en:"stylish and black", jp:"かっこよくてくろいです", stage:3, diff:"easy"},
{type:"te", base:"あかい+まるい", en:"red and round", jp:"あかくてまるいです", stage:3, diff:"easy"},
{type:"te", base:"きいろい+ひろい", en:"yellow and spacious", jp:"きいろくてひろいです", stage:3, diff:"mixed"},
{type:"te", base:"すずしい+たのしい", en:"cool and fun", jp:"すずしくてたのしいです", stage:3, diff:"mixed"},
{type:"te", base:"あたたかい+おもしろい", en:"warm and interesting", jp:"あたたかくておもしろいです", stage:3, diff:"mixed"},
{type:"te", base:"ひろい+ながい", en:"spacious and long", jp:"ひろくてながいです", stage:3, diff:"easy"},
{type:"te", base:"まるい+ちいさい", en:"round and small", jp:"まるくてちいさいです", stage:3, diff:"easy"},
{type:"te", base:"わかい+つよい", en:"young and strong", jp:"わかくてつよいです", stage:3, diff:"mixed"},
{type:"te", base:"めずらしい+すごい", en:"rare and great", jp:"めずらしくてすごいです", stage:3, diff:"mixed"},
{type:"te", base:"ちいさい+まるい", en:"small and round", jp:"ちいさくてまるいです", stage:3, diff:"easy"},
{type:"te", base:"きれい+おしゃれ", en:"beautiful and fashionable", jp:"きれいでおしゃれです", stage:3, diff:"mixed"},
{type:"te", base:"ゆうめい+いろいろ", en:"famous and various", jp:"ゆうめいでいろいろです", stage:3, diff:"mixed"},
{type:"te", base:"げんき+べんり", en:"energetic and convenient", jp:"げんきでべんりです", stage:3, diff:"mixed"},
{type:"te", base:"まっすぐ+しずか", en:"straight and quiet", jp:"まっすぐでしずかです", stage:3, diff:"mixed"},
{type:"te", base:"だいじょうぶ+かんたん", en:"okay and easy", jp:"だいじょうぶでかんたんです", stage:3, diff:"mixed"},
{type:"te", base:"きれい+ゆうめい", en:"beautiful and famous", jp:"きれいでゆうめいです", stage:3, diff:"mixed"},
{type:"te", base:"おしゃれ+いろいろ", en:"fashionable and various", jp:"おしゃれでいろいろです", stage:3, diff:"mixed"},
{type:"te", base:"かわいい+きれい", en:"cute and beautiful", jp:"かわいくてきれいです", stage:3, diff:"easy"},
{type:"te", base:"すごい+ゆうめい", en:"great and famous", jp:"すごくてゆうめいです", stage:3, diff:"mixed"},
{type:"te", base:"たのしい+にぎやか", en:"fun and lively", jp:"たのしくてにぎやかです", stage:3, diff:"mixed"},
{type:"te", base:"あたらしい+べんり", en:"new and convenient", jp:"あたらしくてべんりです", stage:3, diff:"mixed"},
{type:"te", base:"ちいさくておしゃれ", en:"small and fashionable", jp:"ちいさくておしゃれです", stage:3, diff:"easy"},
{type:"te", base:"つよい+げんき", en:"strong and energetic", jp:"つよくてげんきです", stage:3, diff:"mixed"},
{type:"te", base:"ひろい+しずか", en:"spacious and quiet", jp:"ひろくてしずかです", stage:3, diff:"mixed"},
{type:"te", base:"わかい+げんき", en:"young and energetic", jp:"わかくてげんきです", stage:3, diff:"mixed"},
{type:"te", base:"あたたかい+にぎやか", en:"warm and lively", jp:"あたたかくてにぎやかです", stage:3, diff:"mixed"},
{type:"te", base:"めずらしい+ゆうめい", en:"rare and famous", jp:"めずらしくてゆうめいです", stage:3, diff:"mixed"},
{type:"kedo", base:"たかい+べんり", en:"expensive but convenient", jp:"たかいけどべんりなです", stage:4, diff:"mixed"},
{type:"kedo", base:"ふるい+きれい", en:"old but beautiful", jp:"ふるいけどきれいなです", stage:4, diff:"easy"},
{type:"kedo", base:"つよい+むずかしい", en:"strong but difficult", jp:"つよいけどむずかしいです", stage:4, diff:"mixed"},
{type:"kedo", base:"めずらしい+ちいさい", en:"rare but small", jp:"めずらしいけどちいさいです", stage:4, diff:"mixed"},
{type:"kedo", base:"ながい+まるい", en:"long but round", jp:"ながいけどまるいです", stage:4, diff:"easy"},
{type:"kedo", base:"わかい+いそがしい", en:"young but busy", jp:"わかいけどいそがしいです", stage:4, diff:"mixed"},
{type:"kedo", base:"かっこいい+ちいさい", en:"stylish but small", jp:"かっこいいけどちいさいです", stage:4, diff:"easy"},
{type:"kedo", base:"かわいい+あぶない", en:"cute but dangerous", jp:"かわいいけどあぶないです", stage:4, diff:"mixed"},
{type:"kedo", base:"たのしい+むしあつい", en:"fun but humid", jp:"たのしいけどむしあついです", stage:4, diff:"mixed"},
{type:"kedo", base:"あつい+しずか", en:"hot but quiet", jp:"あついけどしずかなです", stage:4, diff:"mixed"},
{type:"kedo", base:"わかい+しずか", en:"young but quiet", jp:"わかいけどしずかなです", stage:4, diff:"mixed"},
{type:"kedo", base:"ちいさい+ゆうめい", en:"small but famous", jp:"ちいさいけどゆうめいなです", stage:4, diff:"mixed"},
];