var langData = {
    ja: {
        title:"形容詞クイズ",
        step1:"レンジ",
        step2:"モード",
        modeStudy:"学習モード（無制限時限）",
        modeChallenge:"チャレンジモード（1問20秒）",
        stageAll:"すべて",
        stage1:"段階1",
        stage2:"段階2",
        stage3:"段階3",
        stage4:"段階4",
        scoreText:"⚡ ",
        timerLabel:"⏰ ",
        inputTip:"漢字不可。丁寧形で入力してください。",
        inputPlaceholder:"ここに答えを入力...",
        kanjiWarn1:"⚠️ 漢字は使わないで！",
        kanjiWarn2:"ひらがなだけで入力してください。",
        plainHint1:"⚠️ 正解ですが...",
        plainHint2:"丁寧形で入力してください。",
        correctTitle:"⭕ 正解",
        wrongTitle:"❌ 違います",
        timeOverTitle:"時間切れ！",
        answerPrefix:"正解：",
        startBtn:"スタート",
        skipBtn:"スキップ",
        checkBtn:"チェック",
        continueBtn:"次へ",
        backBtn:"ホームに戻る",
        endSessionBtn:"セッション終了",
        summaryTitle:"セッション集計",
        sumAttempt:"解答総数：",
        sumCorrect:"正解数：",
        sumWrong:"不正解/スキップ：",
        sumScore:"合計スコア：",
        mistakeHeader:"今回のミス一覧",
        tblEn:"英語意味",
        tblQuestion:"設問",
        tblAnswer:"正解",
        tblUserAns:"自分の答え",
    },
    en: {
        title:"Adjective Quiz",
        step1:"Range",
        step2:"Mode",
        modeStudy:"Study Mode (no timer)",
        modeChallenge:"Challenge Mode (20s per question)",
        stageAll:"All",
        stage1:"Stage 1",
        stage2:"Stage 2",
        stage3:"Stage 3",
        stage4:"Stage 4",
        scoreText:"⚡ ",
        timerLabel:"⏰ ",
        inputTip:"No Kanji. Use polite form.",
        inputPlaceholder:"Answer here...",
        kanjiWarn1:"⚠️ Do not use Kanji!",
        kanjiWarn2:"Please use hiragana only.",
        plainHint1:"⚠️ Correct but...",
        plainHint2:"Please use polite form.",
        correctTitle:"⭕ Correct",
        wrongTitle:"❌ Incorrect",
        timeOverTitle:"Time's up!",
        answerPrefix:"Answer: ",
        startBtn:"Start",
        skipBtn:"Skip",
        checkBtn:"Check",
        continueBtn:"Continue",
        backBtn:"Back Home",
        endSessionBtn:"End Session",
        summaryTitle:"Session Summary",
        sumAttempt:"Attempted: ",
        sumCorrect:"Correct: ",
        sumWrong:"Wrong/Skip: ",
        sumScore:"Score: ",
        mistakeHeader:"Mistakes (this session):",
        tblEn:"En",
        tblQuestion:"Meaning",
        tblAnswer:"Correct",
        tblUserAns:"Your answer",
    }
};