var langData = {
    ja: {
        title:"形容詞クイズ",
        step1:"モード",
        step2:"区分",
        step3:"オプション",
        modeStudy:"学習モード（無制限時限）",
        modeChallenge:"チャレンジモード（1問20秒）",
        sortLesson:"授業進度別",
        sortGrammar:"文法タイプ別",
        sortDiff:"難易度別",
        stage1:"段階1：原形・現在否定形",
        stage2:"段階2：過去形・過去否定形",
        stage3:"段階3：くて・で並列文",
        stage4:"段階4：けど・だけど転折文",
        gOriginal:"原形",
        gNeg:"現在否定",
        gPast:"過去形",
        gTe:"くて・で並列",
        gKedo:"転折文（けど/だけど）",
        diffEasy:"基礎モード",
        diffMixed:"混合モード",
        scoreText:"スコア：",
        timerLabel:"残り時間：",
        inputTip:"漢字不可。丁寧形で入力してください。",
        correctMsg:"せいかい！+10点",
        wrongMsg:"違います！正解：",
        timeOver:"時間切れ！正解：",
        correctTitle:"せいかい！",
        wrongTitle:"ちがいます！",
        timeOverTitle:"時間切れ！",
        answerPrefix:"正解：",
        noteTokui:"※とくいは活用しません",
        startBtn:"スタート",
        skipBtn:"スキップ",
        checkBtn:"チェック",
        continueBtn:"次へ",
        backBtn:"ホームに戻る",
        endSessionBtn:"セッション終了",
        summaryTitle:"セッション集計",
        sumAttempt:"解答総数：",
        sumCorrect:"正解数：",
        sumWrong:"不正解/スキップ：",
        sumScore:"合計スコア：",
        mistakeHeader:"今回のミス一覧",
        tblEn:"英語意味",
        tblQuestion:"設問",
        tblAnswer:"正解",
        tblUserAns:"自分の答え",
        practiceMistakeBtn:"ミス問題を再練習"
    },
    en: {
        title:"Adjective Quiz",
        step1:"Mode",
        step2:"Category",
        step3:"Options",
        modeStudy:"Study Mode (no timer)",
        modeChallenge:"Challenge Mode (20s per question)",
        sortLesson:"By Lesson Progress",
        sortGrammar:"By Grammar Type",
        sortDiff:"By Difficulty",
        stage1:"Stage1: Dictionary & Negative Present",
        stage2:"Stage2: Past & Negative Past",
        stage3:"Stage3: Te Conjunction",
        stage4:"Stage4: Kedo Contrast",
        gOriginal:"Dictionary Form",
        gNeg:"Present Negative",
        gPast:"Past Form",
        gTe:"Te Conjunction",
        gKedo:"Kedo Contrast Sentence",
        diffEasy:"Easy Mode",
        diffMixed:"Mixed Mode",
        scoreText:"Score: ",
        timerLabel:"Remaining Time: ",
        inputTip:"No Kanji. Use polite form.",
        correctMsg:"Correct! +10pts",
        wrongMsg:"Incorrect! Answer: ",
        timeOver:"Time's up! Answer: ",
        correctTitle:"Correct!",
        wrongTitle:"Incorrect!",
        timeOverTitle:"Time's up!",
        answerPrefix:"Answer: ",
        noteTokui:"Note: tokui has no conjugation",
        startBtn:"Start",
        skipBtn:"Skip",
        checkBtn:"Check",
        continueBtn:"Continue",
        backBtn:"Back Home",
        endSessionBtn:"End Session",
        summaryTitle:"Session Summary",
        sumAttempt:"Attempted: ",
        sumCorrect:"Correct: ",
        sumWrong:"Wrong/Skip: ",
        sumScore:"Score: ",
        mistakeHeader:"Mistakes (this session):",
        tblEn:"En",
        tblQuestion:"Meaning",
        tblAnswer:"Correct",
        tblUserAns:"Your answer",
        practiceMistakeBtn:"Practice Mistakes"
    }
};